version: 0.1

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - echo "installing dependencies"
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      - ng build --prod
  post_build:
    commands:
      #- aws s3 rm s3://admin-monitor-suite-masters --recursive
      #- echo S3 bucket is cleared.
      - echo "Build completed on $(date)"
artifacts:
  files:
    - "**/*"
  base-directory: 'dist/'
  discard-paths: no